<template>
    <div class="medium:px-[100px] py-[40px] px-[40px]">
        <div class="bg-[#EDF1FF] rounded-[20px] p-8 font-montserrat">
            <div class="mb-6">
                <h1 class="font-bold text-2xl mb-6">Privacy Policy</h1>
                <p>Thank you for using the Logibug application. We value your privacy and want to explain how we collect,
                    use, and protect your personal information. This Privacy Policy describes our practices regarding the
                    information collected through the Logibug application. By using this application, you agree to the
                    collection and use of your information in accordance with this policy. Please read this privacy policy
                    carefully.</p>
            </div>
            <div class="mb-4">
                <h1 class="font-bold mb-3">Information We Collect:</h1>
                <p>a. Personal Information: We may collect personal information that you provide to us when using the
                    Logibug application. This personal information may include your name, email address, phone number, or
                    other information that you voluntarily provide.</p>
                <p>b. Logibug Information: When you use the Logibug
                    application, we may collect information generated by the application, such as activity logs, date and
                    time of use, type of device you use, operating system, and similar information.</p>
            </div>
            <div class="mb-4">
                <h1 class="font-bold mb-3">Use of Information:</h1>
                <p>a. We use the personal information you provide to operate and improve the Logibug application, as well as
                    to
                    provide the services and support you need.</p>
                <p>b. Log information is used to analyze usage trends, manage the
                    application, diagnose issues, and perform technical maintenance.</p>
            </div>
            <div class="mb-4">
                <h1 class="font-bold mb-3">Information We Collect:</h1>
                <p>a. Personal Information: We may collect personal information that you provide to us when using the
                    Logibug application. This personal information may include your name, email address, phone number, or
                    other information that you voluntarily provide.</p>
                <p>b. Logibug Information: When you use the Logibug
                    application, we may collect information generated by the application, such as activity logs, date and
                    time of use, type of device you use, operating system, and similar information.</p>
            </div>
            <div class="mb-4">
                <h1 class="font-bold mb-3">Information Security:</h1>
                <p>a. We take appropriate security measures to protect your personal information from unauthorized access,
                    unauthorized use, alteration, or unauthorized disclosure.</p>
                <p>b. However, we cannot guarantee complete
                    security against all unforeseen threats or attacks.</p>
            </div>
            <div class="mb-4">
                <h1 class="font-bold mb-3">Changes to the privacy policy:</h1>
                <p>a. We may update this Privacy Policy from time to time. Changes will be effective immediately upon being
                    published in the Logibug application. You are expected to periodically review this Privacy Policy to
                    stay informed of any changes.</p>
            </div>
            <div class="mb-6">
                <h1 class="font-bold mb-3">Contact:</h1>
                <p>
                    If you have any questions or concerns regarding this Privacy Policy, please contact us through the
                    contact information provided in the Logibug application.</p>
            </div>
            <div>
                <p>
                    We hope this Privacy Policy provides a clear understanding of how we collect, use, and protect your
                    personal information when using the Logibug application. Thank you.</p>
            </div>
        </div>
        <div class="flex justify-center mt-2 text-lg">
            <a href="/" class="text-center"><u>Back to Homepage?</u></a>
        </div>
    </div>
</template>

<script>
export default {
    auth: false
}
</script>

<style lang="scss" scoped></style>